spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices
  main:
    allow-bean-definition-overriding: true


server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java.version: @java.version@




